roles:
- - mon.a
  - mds.0
  - osd.0
- - mon.b
  - osd.1
  - osd.2
- - client.0
tasks:
- install:
     extras: yes
- ssh_keys:
- ceph-deploy:
- ceph-fuse:
- workunit:
     clients:
        client.0:
           - suites/blogbench.sh
exclude_arch: armv7l
