overrides:
  ceph-deploy:
    conf:
      mon:
        debug mon: 10
roles:
- - mon.a
  - mds.0
  - osd.0
  - osd.1
  - osd.2
- - mon.b
  - osd.4
  - osd.3
  - osd.5
- - mon.c
  - osd.6
  - osd.7
  - osd.8
- - client.0
tasks:
- install:
     extras: yes
- ssh_keys:
- ceph-deploy:
- ceph-fuse:
- workunit:
     clients:
        client.0:
           - suites/dbench.sh
exclude_arch: armv7l
