tasks:
- full_sequential:
  - radosbench:
      clients: [client.0]
      time: 180
  - radosbench:
      clients: [client.0]
      time: 180
  - radosbench:
      clients: [client.0]
      time: 180
  - radosbench:
      clients: [client.0]
      time: 180
  - radosbench:
      clients: [client.0]
      time: 180
  - radosbench:
      clients: [client.0]
      time: 180
  - radosbench:
      clients: [client.0]
      time: 180
