roles:
    - [mon.0, client.0]
tasks:
    - install:
        # branch has precedence over sha1
        branch: hammer
        sha1: e5b6eea91cc37434f78a987d2dd1d3edd4a23f3f # dumpling
    - exec:
        client.0:
          - ceph --version | grep 'version 0.94'
