tasks:
- install:
- ceph:
- rgw: [client.0]
- workunit:
    clients:
      client.0:
        - rgw/s3_user_quota.pl
overrides:
  ceph:
    conf:
      client:
        rgw relaxed s3 bucket names: true
