tasks:
- install:
- ceph:
- rgw: [client.0]
- s3roundtrip:
    client.0:
      force-branch: ceph-master
      rgw_server: client.0
      roundtrip:
        bucket: rttest
        readers: 10
        writers: 3
        duration: 300
        files:
          num: 10
          size: 2000
          stddev: 500 
