# see http://tracker.ceph.com/issues/20360 and http://tracker.ceph.com/issues/18126
#os_type: centos
# ubuntu and no valgrind until we migrate test to py3
os_type: ubuntu

tasks:
- install:
- ceph: {cluster: c1}
- ceph: {cluster: c2}
- rgw:
    c1.client.0:
      port: 8000
#      valgrind: [--tool=memcheck, --max-threads=1024] # http://tracker.ceph.com/issues/25214
    c1.client.1:
      port: 8001
#      valgrind: [--tool=memcheck, --max-threads=1024]
    c2.client.0:
      port: 8000
#      valgrind: [--tool=memcheck, --max-threads=1024]
    c2.client.1:
      port: 8001
#      valgrind: [--tool=memcheck, --max-threads=1024]
- rgw-multisite:
- rgw-multisite-tests:
    config:
      reconfigure_delay: 60
    args: ['-a', '!bucket_sync_disable'] # filter out disable/enable tests
