overrides:
  ceph:
    log-whitelist:
    - but it is still running
    - overall HEALTH_
    - \(POOL_APP_NOT_ENABLED\)
tasks:
- workunit:
    clients:
      client.0: [rados/load-gen-big.sh]
      client.1: [rados/load-gen-mix.sh]
      client.2: [rados/load-gen-mostlyread.sh]
