overrides:
  ceph:
    log-ignorelist:
    - reached quota
    - but it is still running
    - overall HEALTH_
    - \(POOL_FULL\)
    - \(SMALLER_PGP_NUM\)
    - \(CACHE_POOL_NO_HIT_SET\)
    - \(CACHE_POOL_NEAR_FULL\)
    - \(POOL_APP_NOT_ENABLED\)
    - \(PG_AVAILABILITY\)
    - \(PG_DEGRADED\)
    - \(MON_DOWN\)
    - missing hit_sets
    - do not have an application enabled
    - application not enabled on pool
    - pool application
    - mons down
    - out of quorum
    - needs hit_set_type to be set but it is not
    conf:
      client:
        debug ms: 1
      mon:
        mon warn on pool no app: false
tasks:
- workunit:
    clients:
      client.0:
        - rados/test.sh
        - rados/test_pool_quota.sh

