overrides:
  ceph:
    log-whitelist:
    - '!= best guess digest'
    - '!= best guess data_digest'
    - '!= best guess omap_digest'
    - '!= known digest'
    - '!= known data_digest'
    - '!= known omap_digest'
    - deep-scrub 0 missing, 1 inconsistent objects
    - deep-scrub 1 errors
    - repair 0 missing, 1 inconsistent objects
    - repair 1 errors, 1 fixed
    - shard [0-9]+ missing
    - deep-scrub 1 missing, 0 inconsistent objects
tasks:
- install:
- ceph:
- scrub_test:
