roles:
        - [client.salt_master, mon.a, mgr.x, osd.0, rgw.0, ganesha.0]
        - [client.0]
tasks:
        - deepsea.validation:
        - deepsea.health_ok:
                commands:
                        - health-ok.sh --client-nodes=1 --rgw --min-nodes=2 --nfs-ganesha
