overrides:
  ceph:
    log-ignorelist:
      - Replacing daemon mds
      - \(MDS_INSUFFICIENT_STANDBY\)
      - \(MDS_ALL_DOWN\)
      - \(MDS_UP_LESS_THAN_MAX\)
      - \(MDS_DAMAGE\)
      - \(FS_DEGRADED\)
      - \(MDS_CACHE_OVERSIZED\)
  ceph-fuse:
    disabled: true
tasks:
  - exec:
      mon.a:
        - ceph config set mgr mgr/crash/warn_recent_interval 0
  - cephfs_test_runner:
      fail_on_skip: false
      modules:
        - tasks.cephfs.test_failover

