tasks:
- install:
- ceph:
- ceph-fuse:
- pexec:
    clients:
      - cd $TESTDIR
      - wget http://ceph.com/qa/fsx-mpi.c
      - mpicc fsx-mpi.c -o fsx-mpi 
      - rm fsx-mpi.c
      - ln -s $TESTDIR/mnt.* $TESTDIR/gmnt
- ssh_keys:
- mpi:
    exec: $TESTDIR/fsx-mpi 1MB -N 50000 -p 10000 -l 1048576
    workdir: $TESTDIR/gmnt
- pexec:
    all:
      - rm $TESTDIR/gmnt
      - rm $TESTDIR/fsx-mpi
