tasks:
- install:
    flavor: notcmalloc
    debuginfo: true
- ceph:
    conf:
      client.0: 
        rgw region:  zero
        rgw zone: r0z1
        rgw region root pool: .rgw.region.0
        rgw zone root pool: .rgw.zone.0
        rgw gc pool: .rgw.gc.0
        rgw user uid pool: .users.uid.0
        rgw user keys pool: .users.0
        rgw log data: True
        rgw log meta: True
      client.1: 
        rgw region: one
        rgw zone: r1z1
        rgw region root pool: .rgw.region.1
        rgw zone root pool: .rgw.zone.1
        rgw gc pool: .rgw.gc.1
        rgw user uid pool: .users.uid.1
        rgw user keys pool: .users.1
        rgw log data: False
        rgw log meta: False
- rgw:
    default_idle_timeout: 300
    realm:
      realm0
    regions:
      zero:
        api name: api1
        is master: True
        master zone: r0z1
        zones: [r0z1]
      one:
        api name: api1
        is master: False
        master zone: r1z1
        zones: [r1z1]
    client.0:
      valgrind: [--tool=memcheck]
      system user:
        name: client0-system-user
        access key: 1te6NH5mcdcq0Tc5i8i2
        secret key: 1y4IOauQoL18Gp2zM7lC1vLmoawgqcYPbYGcWfXv
    client.1:
      valgrind: [--tool=memcheck]
      system user:
        name: client1-system-user
        access key: 0te6NH5mcdcq0Tc5i8i2
        secret key: Oy4IOauQoL18Gp2zM7lC1vLmoawgqcYPbYGcWfXv
- radosgw-agent:
    client.0:
      src: client.0
      dest: client.1
      metadata-only: true
- s3tests:
    client.0:
      force-branch: ceph-jewel
      idle_timeout: 300
      rgw_server: client.0
