overrides:
  ceph:
    log-ignorelist:
      - missing required features
tasks:
- exec:
    mon.a:
      - ceph fs dump --format=json-pretty
      - ceph fs set cephfs min_compat_client pacific
- fs.clients_evicted:
