roles:
- - mon.a
  - mon.b
  - mon.c
  - mgr.x
  - osd.0
  - osd.1
  - osd.2
  - client.0
openstack:
  - volumes: # attached to each instance
      count: 3
      size: 10 # GB
tasks:
- install:
- ceph:
    pre-mgr-commands:
      - sudo ceph config set mgr mgr_pool false --force
- workunit:
    clients:
      all:
        - mon/config.sh
