roles:
- - mon.0
  - mon.1
  - mon.2
  - osd.0
  - osd.1
  - osd.2
  - client.0
openstack:
  - volumes: # attached to each instance
      count: 3
      size: 10 # GB
tasks:
- install:
- ceph:
- workunit:
    clients:
      all:
        - mon/test_mon_config_key.py
