overrides:
  ceph_ansible:
    rhbuild: '2.2'
    vars:
      ceph_conf_overrides:
          global:
            osd default pool size: 2
            osd pool default pg num: 64
            osd pool default pgp num: 64
            mon max pg per osd: 1024
      ceph_stable_release: luminous
      ceph_origin: distro
      ceph_stable: true
      ceph_stable_rh_storage: true
      ceph_test: true
      journal_size: 1024
      osd_auto_discovery: false
      osd_scenario: collocated
tasks:
- ssh-keys:
- ceph-ansible:
- install.ship_utilities:
- systemd:
- workunit:
    clients:
      all:
      - rados/load-gen-mix.sh
