overrides:
  ceph:
    log-whitelist:
      - overall HEALTH_
      - \(CACHE_POOL_NO_HIT_SET\)
      - \(POOL_APP_NOT_ENABLED\)
tasks:
- workunit:
    clients:
      client.0:
        - rbd/test_librbd.sh
