tasks:
- ssh-keys: null
- ceph-ansible: null
- rgw-system-test:
    test-name: test_Mbuckets_with_Nobjects_shards
    config:
      shards: 100
      max_objects: 24   # max objects per bucket.
      user_count: 25
      bucket_count: 25
      objects_count: 25
      min_file_size: 50
      max_file_size: 60