tasks:
- ssh-keys: null
- ceph-ansible: null
- rgw-system-test:
    test-name: test_multipart_upload_download
    config:
       user_count: 25
       bucket_count: 25
       min_file_size: 50
       max_file_size: 60