tasks:
- ssh-keys: null
- ceph-ansible: null
- rgw-system-test:
    test-name: test_version_with_revert
    config:
       user_count: 25
       bucket_count: 25
       objects_count: 90
       version_count: 5
       min_file_size: 50
       max_file_size: 60