overrides:
  ceph:
    conf:
      global:
        ms inject delay max: 1
        ms inject delay probability: 0.005
        ms inject delay type: osd
        ms inject internal delays: 0.002
        ms inject socket failures: 2500
tasks:
- install: null
- ceph:
    fs: xfs
    log-whitelist:
      - overall HEALTH_
      - \(OSDMAP_FLAGS\)
      - \(OSD_
      - \(PG_
      - \(POOL_
      - \(CACHE_POOL_
      - \(SMALLER_PGP_NUM\)
      - \(OBJECT_
      - \(REQUEST_SLOW\)
      - \(TOO_FEW_PGS\)
- radosbench:
    clients: [client.0]
    time: 150
