overrides:
  ceph:
    log-whitelist:
      - reached quota
      - mons down
      - overall HEALTH_
      - \(OSDMAP_FLAGS\)
      - \(OSD_
      - \(PG_
      - \(POOL_
      - \(CACHE_POOL_
      - \(SMALLER_PGP_NUM\)
      - \(OBJECT_
      - \(SLOW_OPS\)
      - \(TOO_FEW_PGS\)
      - \(OSD_SLOW_PING_TIME
    conf:
      global:
        ms inject delay max: 1
        ms inject delay probability: 0.005
        ms inject delay type: mon
        ms inject internal delays: 0.002
        ms inject socket failures: 2500
        mon client directed command retry: 5
tasks:
- install: null
- ceph:
    fs: xfs
- mon_thrash:
    revive_delay: 90
    thrash_delay: 1
    thrash_many: true
- workunit:
    clients:
      client.0:
      - rados/test.sh
