tasks:
- install:
- ceph:
    fs: ext4
    log-ignorelist:
    - but it is still running
    - overall HEALTH_
    - \(POOL_APP_NOT_ENABLED\)
- ceph-fuse:
- workunit:
    clients:
      all:
        - rados/load-gen-mix.sh
