tasks:
- install: null
- ceph:
    fs: ext4
    log-whitelist:
    - reached quota
    - but it is still running
    - objects unfound and apparently lost
    - (POOL_APP_NOT_ENABLED)
    - 'noscrub flag(s) set'
- thrashosds:
    chance_pgnum_grow: 2
    chance_pgpnum_fix: 1
    timeout: 1200
- workunit:
    clients:
      client.0:
      - rados/test.sh
