overrides:
   rgw:
    ec-data-pool: true
    cache-pools: true
    frontend: civetweb
tasks:
- install:
- ceph:
- rgw: [client.0]
- s3tests:
    client.0:
      rgw_server: client.0
overrides:
  ceph:
    conf:
      client:
        rgw lc debug interval: 10
        rgw crypt s3 kms encryption keys: testkey-1=YmluCmJvb3N0CmJvb3N0LWJ1aWxkCmNlcGguY29uZgo= testkey-2=aWIKTWFrZWZpbGUKbWFuCm91dApzcmMKVGVzdGluZwo=
        rgw crypt require ssl: false
