tasks:
- tox: [ client.0 ]
- keycloak:
    client.0:
      keycloak_version: 11.0.0
- s3tests:
    client.0:
      sts_tests: True
      force-branch: ceph-quincy
      rgw_server: client.0
      extra_attrs: ['webidentity_test']
overrides:
  ceph:
    conf:
      client:
              rgw sts key: abcdefghijklmnop
              rgw s3 auth use sts: true
