meta:
- desc: |
   install ceph/pacific latest
tasks:
- install:
    branch: pacific
    exclude_packages:
      - librados3
      - ceph-mgr-dashboard
      - ceph-mgr-diskprediction-local
      - ceph-mgr-rook
      - ceph-mgr-cephadm
      - cephadm
      - ceph-volume
    extra_packages: ['librados2']
- print: "**** done installing pacific"
- ceph:
    log-ignorelist:
      - overall HEALTH_
      - \(FS_
      - \(MDS_
      - \(OSD_
      - \(MON_DOWN\)
      - \(CACHE_POOL_
      - \(POOL_
      - \(MGR_DOWN\)
      - \(PG_
      - \(SMALLER_PGP_NUM\)
      - Monitor daemon marked osd
      - Behind on trimming
      - Manager daemon
    conf:
      global:
        mon warn on pool no app: false
        ms bind msgr2: false
- exec:
    osd.0:
      - ceph osd set-require-min-compat-client pacific
- print: "**** done ceph"
