# for now, s3-tests requires py2
os_type: ubuntu
tasks:
- install:
- ceph:
- dnsmasq:
    client.0:
      s3.: client.0
      s3-website.: client.1
- rgw:
    client.0:
      dns-name: s3.
    client.1:
      dns-s3website-name: s3-website.
- s3tests:
    client.0:
      git_remote: git://github.com/theanalyst/
      force-branch: public-access-qa
      rgw_server: client.0
      rgw_website_server: client.1
