tasks:
- install:
- ceph:
- dnsmasq:
    client.0:
      s3.: client.0
      s3-website.: client.1
- rgw:
    client.0:
      dns-name: s3.
    client.1:
      dns-s3website-name: s3-website.
- s3tests:
    client.0:
      force-branch: ceph-quincy
      rgw_server: client.0
      rgw_website_server: client.1
