tasks:
- ssh-keys: null
- ceph-ansible:
    cluster: c1
- ceph-ansible:
    cluster: c2
- install.ship_utilities: null
- new-rgw-multisite:
   realm:
     name: test-realm
     is_default: true
   zonegroups:
     - name: test-zg
       is_master: true
       is_default: true
       zones:
         - name: zone1
           is_master: true
           is_default: true
           endpoints: [c1.rgw.0]
         - name: zone2
           is_default: true
           endpoints: [c2.rgw.1]
- netem:
    clients: [c1.rgw.0]
    iface: eno1
    dst_client: c2.rgw.1
    delay_range: [30ms, 100ms]
- multisite-test.userexec:
      master_client: c1.rgw.0
      test_dir_version: v1
      master_config:
        user_count: 3
- sleep:
      duration: 60
- multisite-test:
      test-name: test_Mbuckets_with_Nobjects
      test_dir_version: v1
      test_client: c2.rgw.1
      bucket_count: 2
      objects_count: 2
      min_file_size: 5
      max_file_size: 10
- sleep:
      duration: 60
- new-rgw-multisite.addzone:
      name: zone3
      endpoints: c1.rgw.1
- multisite-test:
      test-name: test_Mbuckets_with_Nobjects
      test_dir_version: v1
      test_client: c2.rgw.1
      bucket_count: 2
      objects_count: 2
      min_file_size: 5
      max_file_size: 10
- sleep:
      duration: 120
- multisite-test.pull-io-info:
- verify-io:
      verification_script: read_io_info
- new-rgw-multisite.failover:
      new_master_zone: zone3
      new_master: c1.rgw.1
- multisite-test:
      test-name: test_Mbuckets_with_Nobjects
      test_dir_version: v1
      test_client: c2.rgw.1
      bucket_count: 2
      objects_count: 2
      min_file_size: 5
      max_file_size: 10
- sleep:
      duration: 120
- multisite-test.pull-io-info:
- verify-io:
      verification_script: read_io_info

