tasks:
- ssh-keys: null
- ceph-ansible:
    cluster: c1
- ceph-ansible:
    cluster: c2
- install.ship_utilities: null
- new-rgw-multisite:
   realm:
     name: test-realm
     is_default: true
   zonegroups:
     - name: test-zg
       is_master: true
       is_default: true
       zones:
         - name: test-zone
           is_master: true
           is_default: true
           endpoints: [c1.rgw.0]
         - name: test-zone2
           is_default: true
           endpoints: [c2.rgw.1]
- netem:
    clients: [c1.rgw.0]
    iface: eno1
    dst_client: c2.rgw.1
    delay_range: [20ms, 40ms]
- multisite-test.userexec:
      master_client: c1.rgw.0
      test_dir_version: v1
      master_config:
        user_count: 3
- sleep:
      duration: 60
- multisite-test:
      test-name: test_Mbuckets
      test_dir_version: v1
      test_client: c2.rgw.1
      bucket_count: 5
- sleep:
      duration: 120
- multisite-test.pull-io-info:
- verify-io:
      verification_script: read_io_info