overrides:
  ceph:
    conf:
      global:
        bluestore warn on legacy statfs: false

tasks:
- mds_pre_upgrade:
- print: "**** done mds pre-upgrade sequence"
- install.upgrade:
    mon.a:
    mon.b:
- print: "**** done install.upgrade both hosts"
- ceph.stop: [mds.*]
- ceph.restart:
    daemons: [mon.*, mgr.*, osd.*, mds.*]
    mon-health-to-clog: false
- print: "**** done ceph.restart"
