tasks:
- install:
- ceph:
- rgw: [client.0]
- exec:
    client.0:
      - sudo chmod 0777 /var/lib/ceph
      - sudo chmod 0777 /var/lib/ceph/radosgw
      - sudo chmod 0777 /var/lib/ceph/radosgw/dbstore-default_ns.db
- s3tests:
    client.0:
      force-branch: ceph-master
      dbstore_tests: True
      rgw_server: client.0
      extra_attrs: ["!fails_on_rgw,!fails_on_dbstore"]

