overrides:
  ceph:
    log-whitelist:
      - reached quota
      - overall HEALTH_
      - (CACHE_POOL_NO_HIT_SET)
      - (POOL_FULL)
      - (SMALLER_PGP_NUM)
      - (REQUEST_SLOW)
      - (CACHE_POOL_NEAR_FULL)
    conf:
      client:
        debug ms: 1
        debug objecter: 20
        debug rados: 20
        debug monc: 20
tasks:
- workunit:
    timeout: 6h
    clients:
      client.0:
        - rados/test.sh
