overrides:
  ceph:
    log-ignorelist:
    - SLOW_OPS
    - slow request
    conf:
      osd:
        filestore flush min: 0
tasks:
- workunit:
    clients:
      all:
        - suites/ffsb.sh
    timeout: 5h
