teuthology:
  postmerge:
    - if yaml.teuthology.variables.fail_fs then reject() end

meta:
- desc: |
   setup ceph/pacific v16.2.4

tasks:
# Disable metrics sending by kclient as it may crash (assert) a v16.2.4 MDS
- pexec:
    clients:
      - sudo modprobe -r ceph
      - sudo modprobe ceph disable_send_metrics=on
- install:
    tag: v16.2.4
    exclude_packages:
      - ceph-volume
- print: "**** done install task..."
- cephadm:
    roleless: true
    image: quay.io/ceph/ceph:v16.2.4
    cephadm_branch: v16.2.4
    cephadm_git_url: https://github.com/ceph/ceph
    # needed for v16.2.4 due to --skip-admin-label
    avoid_pacific_features: true
- print: "**** done starting v16.2.4"
- cephadm.shell:
    host.a:
      - ceph orch status
      - ceph orch ps
      - ceph orch ls
      - ceph orch host ls
      - ceph orch device ls
