
overrides:
  ceph:
    log-whitelist:
      - bad backtrace
      - object missing on disk
      - error reading table object
      - error reading sessionmap
      - unmatched fragstat
      - unmatched rstat
      - was unreadable, recreating it now
      - Scrub error on inode
      - Metadata damage detected
      - MDS_FAILED
      - MDS_DAMAGE

tasks:
  - cephfs_test_runner:
      modules:
        - tasks.cephfs.test_recovery_pool
