overrides:
  ceph:
    log-whitelist:
      - Scrub error on inode
      - Behind on trimming
      - Metadata damage detected
      - overall HEALTH_
      - (MDS_TRIM)
    conf:
      mds:
        mds log max segments: 1
        mds cache max size: 1000
tasks:
- cephfs_test_runner:
    modules:
      - tasks.cephfs.test_scrub_checks
