
overrides:
  ceph:
    log-whitelist:
      - responding to mclientcaps\(revoke\)
      - not advance its oldest_client_tid
      - failing to advance its oldest client/flush tid
      - Too many inodes in cache
      - failing to respond to cache pressure
      - slow requests are blocked
      - failing to respond to capability release
      - MDS cache is too large
      - \(MDS_CLIENT_OLDEST_TID\)
      - \(MDS_CACHE_OVERSIZED\)

tasks:
  - cephfs_test_runner:
      modules:
        - tasks.cephfs.test_client_limits
