overrides:
  ceph:
    conf:
      mgr:
        debug client: 10
    log-whitelist:
      - OSD full dropping all updates
      - OSD near full
      - pausewr flag
      - failsafe engaged, dropping updates
      - failsafe disengaged, no longer dropping
      - is full \(reached quota
      - POOL_FULL
      - POOL_BACKFILLFULL

tasks:
  - cephfs_test_runner:
      modules:
        - tasks.cephfs.test_volumes
