overrides:
  ceph:
    log-ignorelist:
    - \(POOL_APP_NOT_ENABLED\)
    conf:
      global:
        enable experimental unrecoverable data corrupting features: crimson
      mon:
        osd pool default crimson: true
      osd:
        crimson osd obc lru size: 10
        debug ms: 20
        seastore cache lru size: 64M
        seastore max concurrent transactions: 8
        osd op complaint time: 60
  workunit:
    env:
      CRIMSON_COMPAT: '1'
