overrides:
  ceph:
    log-ignorelist:
    - \(POOL_APP_NOT_ENABLED\)
    conf:
      global:
        enable experimental unrecoverable data corrupting features: crimson
      mon:
        osd pool default crimson: true
      osd:
        crimson osd obc lru size: 10
        debug ms: 20
        seastore cachepin size pershard: 64M
        seastore max concurrent transactions: 8
    crimson_compat: true

  cephadm:
    crimson_compat: true
  cephadm.apply:
    specs:
      - service_type: osd
        service_id: osd.crimson
        placement:
          host_pattern: "*"
        data_devices:
          all: true
        extra_container_args:
          - "-v"
          - "/usr/bin/ceph-osd-crimson:/usr/bin/ceph-osd"

  workunit:
    env:
      CRIMSON_COMPAT: '1'
