overrides:
  ceph:
    log-whitelist:
    - SLOW_OPS
    - slow request
    conf:
      osd:
        filestore flush min: 0
        osd heartbeat grace: 60
tasks:
- check-counter:
    counters:
      mds:
        - "mds.dir_split"
- workunit:
    clients:
      all:
        - suites/ffsb.sh
