overrides:
  ceph:
    log-ignorelist:
    - SLOW_OPS
    - slow request
tasks:
- check-counter:
    counters:
      mds:
        - "mds.dir_split"
- workunit:
    clients:
      all:
        - suites/ffsb.sh
