overrides:
  ceph:
    log-ignorelist:
      - overall HEALTH_
      - \(MON_DOWN\)
      - DISPATCH_QUEUE_THROTTLE
tasks:
- mon_thrash:
    check_mds_failover: True
    revive_delay: 20
    thrash_delay: 10
