
# The task interferes with the network, so we need
# to permit OSDs to complain about that.
overrides:
  ceph:
    log-ignorelist:
      - but it is still running
      - slow request
      - evicting unresponsive client

tasks:
  - cephfs_test_runner:
      fail_on_skip: false
      modules:
        - tasks.cephfs.test_client_recovery
