nuke-on-error: false
overrides:
  nuke-on-error: false
tasks:
- ceph-fuse:
- print: "**** done nautilus client"
#- workunit:
#    clients:
#      all:
#      - suites/fsstress.sh
- print: "**** done fsstress"
