tasks:
- install:
- exec:
    mon.b:
    - date -u -s @$(expr $(date -u +%s) + 2)
- ceph:
    wait-for-healthy: false
    log-whitelist:
    - .*clock.*skew.*
    - clocks not synchronized
    - overall HEALTH_
    - \(MON_CLOCK_SKEW\)
    - \(MGR_DOWN\)
    - \(PG_
    - \(SLOW_OPS\)
    - No standby daemons available
- mon_clock_skew_check:
    expect-skew: true
