roles:
- - mon.a
  - mds.a
  - osd.0
  - osd.1
- - mon.b
  - mon.c
  - osd.2
  - osd.3
  - client.0

openstack:
- volumes: # attached to each instance
    count: 2
    size: 10 # GB

tasks:
- install:
- ceph:
    fs: xfs
    log-whitelist:
    - wrongly marked me down
    conf:
      client.rest0:
        debug ms: 1
        debug objecter: 20
        debug rados: 20
- rest-api: [client.0]
- workunit:
    clients:
      client.0:
         - rest/test.py
