tasks:
- install:
- ceph:
- kclient: [client.0]
- knfsd: [client.0]
- nfs:
    client.1:
        server: client.0
        options: [rw,hard,intr,nfsvers=3]
- workunit:
    clients:
        client.1:
            - suites/ffsb.sh
