
tasks:
  - install:
  - ceph:
      # tests may leave mgrs broken, so don't try and call into them
      # to invoke e.g. pg dump during teardown.
      wait-for-scrub: false
      log-whitelist:
        - overall HEALTH_
        - \(MGR_DOWN\)
        - \(PG_
        - replacing it with standby
        - No standby daemons available
        - Reduced data availability
        - Degraded data redundancy
        - objects misplaced
        - Synthetic exception in serve
        - influxdb python module not found
        - \(MGR_ZABBIX_
        - foo bar
        - Failed to open Telegraf
        - evicting unresponsive client
  - cephfs_test_runner:
      modules:
        - tasks.mgr.test_module_selftest
