tasks:
  - install:
  - ceph:
      # tests may leave mgrs broken, so don't try and call into them
      # to invoke e.g. pg dump during teardown.
      wait-for-scrub: false
      log-whitelist:
        - overall HEALTH_
        - \(MGR_DOWN\)
        - \(PG_
        - replacing it with standby
        - No standby daemons available
  - workunit:
      clients:
        client.0:
          - mgr