tasks:
- ssh-keys:
- ceph-ansible:
- install.ship_utilities:
- full_sequential:
  - radosbench:
      clients: [client.0]
      time: 90
  - radosbench:
      clients: [client.0]
      time: 90
  - radosbench:
      clients: [client.0]
      time: 90
  - radosbench:
      clients: [client.0]
      time: 90
  - radosbench:
      clients: [client.0]
      time: 90
  - radosbench:
      clients: [client.0]
      time: 90
  - radosbench:
      clients: [client.0]
      time: 90
  - radosbench:
      clients: [client.0]
      time: 90
