overrides:
  ceph:
    log-ignorelist:
    - but it is still running
    - overall HEALTH_
    - \(OSDMAP_FLAGS\)
    - \(PG_
    - \(OSD_
    - \(OBJECT_
    - \(POOL_APP_NOT_ENABLED\)
  install:
    ceph:
      extra_system_packages:
      - python3-pytest
tasks:
- workunit:
    timeout: 1h
    clients:
      client.0:
        - rados/test_python.sh -m 'not (wait or tier or ec or bench or stats)'
