overrides:
  ceph:
    log-ignorelist:
    - but it is still running
    - overall HEALTH_
    - \(OSDMAP_FLAGS\)
    - \(PG_
    - \(OSD_
    - \(OBJECT_
    - \(POOL_APP_NOT_ENABLED\)
tasks:
- workunit:
    clients:
      client.0:
        - rados/test_python.sh --eval-attr 'not (wait or tier or snap or ec or bench or stats)'
