---
name: "Check Incompatible Licenses"
on: [pull_request]

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
    - name: Check Pull Request
      uses: JJ/github-pr-contains-action@bdece3f70a1f1d147ca756552ff357f4755f0755  # releases/v14.1
      with:
        github-token: ${{github.token}}
        diffDoesNotContain: "GNU General Public License"
