name: Check ceph config changes

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - reopened

permissions:
  issues: write
  contents: read
  pull-requests: write

jobs:
  pull_request:
    runs-on: ubuntu-latest

    env:
      PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_COMMITS: ${{ github.event.pull_request.commits }}
      BASE_REPO_URL: ${{ github.event.pull_request.base.repo.clone_url }}
      BASE_REF: ${{ github.event.pull_request.base.ref }}
      HEAD_REPO_URL: ${{ github.event.pull_request.head.repo.clone_url }}

    steps:
      - name: Checkout ceph.git
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ceph
          sparse-checkout: |
            src/script
            src/common/options
            .github/workflows

      - name: Get common ancestor between PR and ceph upstream main branch
        id: get_common_ancestor
        working-directory: ceph
        env:
          BRANCH_PR: origin/${{ github.event.pull_request.head.ref }}
        run: |
          set -euo pipefail
          FETCH_DEPTH=$(( PR_COMMITS + 1 ))
          REFSPEC="+${PR_HEAD_SHA}:remotes/origin/pr/${PR_NUMBER}/head"
          
          git fetch origin "$REFSPEC" \
            --depth="$FETCH_DEPTH" \
            --no-tags \
            --prune \
            --no-recurse-submodules
        
          COMMON_ANCESTOR_SHA=$(git rev-list \
            --first-parent \
            --max-parents=0 \
            --max-count=1 \
            "origin/pr/${PR_NUMBER}/head")

          echo "COMMON_ANCESTOR_SHA=$COMMON_ANCESTOR_SHA" >> "$GITHUB_ENV"

      - name: Setup Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: '3.13'

      - name: Install python packages
        working-directory: ceph
        run: |
          pip3 install -r ./src/script/config-diff/requirements.txt

      - name: Execute config diff tool
        id: diff_tool
        working-directory: ceph
        env:
          REF_REPO: ${{ github.event.pull_request.base.repo.clone_url }}
          REF_BRANCH: ${{ github.event.pull_request.base.ref }}
          REF_COMMIT_SHA: ${{ env.COMMON_ANCESTOR_SHA }}
          REMOTE_REPO: ${{ github.event.pull_request.head.repo.clone_url }}
          REMOTE_BRANCH: ${{ github.event.pull_request.head.ref }}
          REMOTE_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          set -euo pipefail

          {
            echo 'DIFF_JSON<<EOF'
            python3 ./src/script/config-diff/config_diff.py \
              diff-branch-remote-repo \
              --ref-branch "$REF_BRANCH" \
              --ref-commit-sha "$REF_COMMIT_SHA" \
              --remote-repo "$REMOTE_REPO" \
              --cmp-branch "$REMOTE_BRANCH" \
              --cmp-commit-sha "$REMOTE_COMMIT_SHA" \
              --format=posix-diff \
              --skip-clone
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Post output as a comment
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DIFF_JSON_OUTPUT: ${{ steps.diff_tool.outputs.DIFF_JSON }}
        with:
          script: |
            const configDiff = process.env.DIFF_JSON_OUTPUT;
            const postComment = require('./ceph/.github/workflows/scripts/config-diff-post-comment.js');
            postComment({ github, context, core, configDiff });
