name: Build ceph for ppc64le
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: mock env
        run: |
          ./do_cmake.sh
          cd build
          ninja -j4
          ninja install
          ctest -j$(nproc)
        shell: bash
      - run: echo "üçè This job's status is ${{ job.status }}."