---
name: "Check for missing .qa links"
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - reopened

jobs:
  pull_request:
    name: "Check for missing .qa links"
    runs-on: ubuntu-latest
    if: github.repository == 'ceph/ceph'
    steps:
      - name: Checkout main branch for pull_request_target
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: 'refs/heads/main'
          path: main

      - name: checkout PR HEAD
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: pull_request

      - name: verify .qa links
        run: ../main/src/script/verify-qa
        working-directory: pull_request/
