tasks:
  - deepsea_deploy:
      cli: true
      commands:
        - stage0:
        - stage1:
        - policy_cfg:
            profile: default
        - stage2:
        - stage3:
        - 'ceph -s'
