tasks:
        - deepsea.preflight:
        - deepsea.orch:
                stage: prep
        - deepsea.orch:
                stage: 1
        - deepsea.policy:
                profile: default
        - deepsea.orch:
                stage: 2
        - deepsea.orch:
                stage: 3
        - exec:
                client.salt_master:
                        - 'ceph -s'
