tasks:
- ssh-keys: null
- ceph-ansible:
      cluster: c1
- ceph-ansible:
      cluster: c2
- install.ship_utilities: null
- new-rgw-multisite:
   realm:
     name: test-realm
     is_default: true
   zonegroups:
     - name: test-zg
       is_master: true
       is_default: true
       zones:
         - name: test-zone
           is_master: true
           is_default: true
           endpoints: [c1.rgw.0, c1.rgw.1]
         - name: test-zone2
           is_default: true
           endpoints: [c2.rgw.0, c2.rgw.1]
- multisite-test.userexec:
      master_client: c1.rgw.0
      test_dir_version: v1
      master_config:
        user_count: 3
- sleep:
      duration: 60
- netem:
    clients: [c1.rgw.0]
    iface: eno1
    dst_client: c2.rgw.1
    link_toggle_interval: 5  # no need to mention units. Dafault takes seconds.
- sleep:
      duration: 5
- multisite-test:
      test-name: test_multipart_upload
      test_dir_version: v1
      test_client: c1.haproxy.0
      target_config:
          bucket_count: 5
          min_file_size: 5
          max_file_size: 10
- sleep:
      duration: 120
- netem:
    clients: [c1.rgw.0]
    iface: eno1
    link_recover: true
- multisite-test.pull-io-info:
- verify-io:
      verification_script: read_io_info

