tasks:
- ssh-keys: null
- ceph-ansible:
      cluster: c1
- ceph-ansible:
      cluster: c2
- install.ship_utilities: null
- new-rgw-multisite:
   realm:
     name: test-realm
     is_default: true
   zonegroups:
     - name: test-zg
       is_master: true
       is_default: true
       zones:
         - name: test-zone
           is_master: true
           is_default: true
           endpoints: [c1.rgw.0, c1.rgw.1]
         - name: test-zone2
           is_default: true
           endpoints: [c2.rgw.0, c2.rgw.1]
- multisite-test.userexec:
      master_client: c1.rgw.0
      test_dir_version: v1
      master_config:
        user_count: 3
- sleep:
      duration: 60
- ceph-ipmi.poweroff: [c1.rgw.1]
- sleep:
      duration: 90
- multisite-test:
      test-name: test_Mbuckets_with_Nobjects
      test_dir_version: v1
      test_client: c1.haproxy.0
      bucket_count: 5
      objects_count: 5
      min_file_size: 5
      max_file_size: 10
- sleep:
      duration: 60
- multisite-test.pull-io-info:
- verify-io:
      verification_script: read_io_info
- ceph-ipmi.poweron: [c1.rgw.1]